sap.ui.define([
    "test/incentergy/ol/Feature",
    "test/incentergy/ol/layer/Layer",
    "test/incentergy/ol/layer/Vector",
    "test/incentergy/ol/layer/Base",
    "test/incentergy/ol/layer/Tile",
    "test/incentergy/ol/style/Style",
    "test/incentergy/ol/style/Fill",
    "test/incentergy/ol/style/Stroke",
    "test/incentergy/ol/geom/Geometry",
    "test/incentergy/ol/geom/Circle",
    "test/incentergy/ol/geom/SimpleGeometry",
    "test/incentergy/ol/interaction/Select",
    "test/incentergy/ol/library",
    "test/incentergy/ol/Map",
    "test/incentergy/ol/source/UrlTile",
    "test/incentergy/ol/source/Source",
    "test/incentergy/ol/source/OSM",
    "test/incentergy/ol/source/Vector",
    "test/incentergy/ol/source/TileImage",
    "test/incentergy/ol/source/Image",
    "test/incentergy/ol/source/ImageWMS",
    "test/incentergy/ol/source/XYZ",
    "test/incentergy/ol/source/Tile",
    "test/incentergy/ol/source/TileWMS",
    "test/incentergy/ol/source/BingMaps"
], function() {
    "use strict";
});